### ISSUE TITLE
Free For All Random Battles

### ISSUE THREAD

**Issue by maugen93** [pkmn/randbats#1]
Hello, i'm interested to free-for-all random battles json data. Will they be added in future?
Thank you

**Comment by scheibo** [comment]
Sorry for the delay in responding to this - I wasn't 'Watching' this repo by default :(

I actually deliberately disabled multi random battle generation in https://github.com/pkmn/randbats/commit/24d2dda7deace59e303d703c5850475e8b2608e2 - the sets used in the multi formats are currently the same as `gen8doublesrandombattle`, with the exception that in multi you need to prune Ally Switch from any movepool that would otherwise have it. https://github.com/smogon/pokemon-showdown/blob/master/data/random-teams.ts#L1706. This is also the same reason monotype "isn't supported" - the sets are the same as singles just all one type. If and when FFA/multi battles have different sets I'll add support for it. Cheers.

**Comment by maugen93** [comment]
Thank you a lot :)
